### PR TITLE
add panduza local broker discovery service function to script

### LINKED ISSUE #90: Append the LSD mechanism
Script users would appreciate the ease of using LSD mechanism with their tests scripts.

### PR DESCRIPTION
**Pull request by Darcraytore1**

### CODE REVIEW

**Comment by XdoctorwhoZ** [comment]
Ok, I understand, it was not what I wanted but my issue is not very clear.

I will specify something more accurate.

**Comment by XdoctorwhoZ** [comment]
But it is a good start

**Comment by Darcraytore1** [comment]
@XdoctorwhoZ The client can be created easier without having to know anything while a platform is running on the local network. User can also precise a platform_name if is looking for a specific platform.

**Comment by Darcraytore1** [comment]
No sorry I didn't say anything I still have to make it work with the alias mechanism.

**Comment by Darcraytore1** [comment]
Maybe I didn't see it but if it didn't exist, need to add a big documentation about how to use scripts in user guide

**Comment by Darcraytore1** [comment]
I think this pull request can be merge

**Pull request merged**
